### ISSUE TITLE
Execution status is running but the execution hasn't been created on wings

### ISSUE THREAD

**Issue by mosoriob** [KnowledgeCaptureAndDiscovery/DISK-WEB#55]
**Describe the bug**
I have triggered the Bikes Rental LOI on disk.isi.edu and the UI tells me that it is running but that is not true.

DISK logs tell me (you can see the full logs at the bottom):
1. https://github.com/KnowledgeCaptureAndDiscovery/DISK-WEB/blob/7039e9089b2f0f5062217d161b43367466c9c4c2/server/src/main/java/org/diskproject/server/repository/WingsAdapter.java#L340
2. https://github.com/KnowledgeCaptureAndDiscovery/DISK-WEB/blob/7039e9089b2f0f5062217d161b43367466c9c4c2/server/src/main/java/org/diskproject/server/repository/WingsAdapter.java#L377

The wings server is not responding to errors.

**To Reproduce**
1. Go to https://disk.isi.edu/hypotheses/Hypothesis-6f28AYbUooqn
2. Click on update

**Expected behavior**
- If DISK can't obtain the execution status information, the execution status must be FAILED
- If the creation of the workflow fails, the DISK server sends the error message and the UI shows it.

**Additional context**

Wings server: https://wings.disk.isi.edu/wings-portal/
Version: 5.2.0

DISK logs

```bash
Run ID bikes-189a83d4-0b52-478d-9c36-2cdc62db763b: No execution information
Run ID bikes-189a83d4-0b52-478d-9c36-2cdc62db763b: No variables attribute
Link: https://wings.disk.isi.edu/wings-portal/users/admin/bikes/executions?run_id=https%3A%2F%2Fwings.disk.isi.edu%2Fwings-portal%2Fexport%2Fusers%2Fadmin%2Fbikes%2Fexecutions%2Fbikes-189a83d4-0b52-478d-9c36-2cdc62db763b.owl%23bikes-189a83d4-0b52-478d-9c36-2cdc62db763b
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.diskproject.shared.classes.workflow.WorkflowRun.getStatus()" is null
at org.diskproject.server.repository.DiskRepository$TLOIMonitoringThread.run(DiskRepository.java:1897)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mosoriob** [comment]
if we don't have execution information, do we have an error?

**Comment by mosoriob** [comment]
https://wings.disk.isi.edu/wings-portal/sparql?query=select+%3Fa+%3Fb+%3Fc+%7B%0D%0A%3Chttp%3A%2F%2Flocalhost%3A8080%2Fwings-portal%2Fexport%2Fusers%2Fadmin%2Fbikes%2Fexecutions%2Fbikes-f4e2da8e-1233-4136-83dc-af9054df542a.owl%23bikes-f4e2da8e-1233-4136-83dc-af9054df542a%3E+++++%3Fb+%3Fc%0D%0A%7D+LIMiT+10000&update=

https://wings.disk.isi.edu/wings-portal/sparql?query=select+%3Fa+%3Fb+%3Fc+%7B%0D%0A%3Chttp%3A%2F%2Flocalhost%3A8080%2Fwings-portal%2Fexport%2Fusers%2Fadmin%2Fbikes%2Fexecutions%2Fbikes-74f7b89a-535a-46fc-bcc9-ea2be999dba3.owl%23bikes-74f7b89a-535a-46fc-bcc9-ea2be999dba3%3E++++%3Fb+%3Fc%0D%0A%7D+LIMiT+10000&update=

**Comment by mosoriob** [comment]
I can confirm that a wings misconfiguration causes this issue.

Details:

I have created a new instance of wings with the correct configuration and it is running at wings.dev.disk.isi.edu. Also, I tried to export the domain, replace the URL and import it but it didn't work. 

Finally, I did the component and workflow starting from a new domain and this error doesn't appear.

**Comment by mosoriob** [comment]
@hvarg what is the status of this? can we use wings misconfigured?
